import { createHmac } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { DEMO_CATALOG } from "@/lib/catalog";
import { verifyCommerceAuditChain } from "@/lib/commerce-audit";
import { buildCart, emptyPreferenceProfile, isProfileComplete, nextQuestion, rankProducts, recommendedAddons, validateCart } from "@/lib/commerce-policy";
import { createMachineCheckout, createMachineQuote, executeShoppingCommand, markSelectedItemUnavailable, processRazorpayWebhook, sendShoppingMessage } from "@/lib/commerce-service";
import { createOperatorToken, verifyAccessCode, verifyOperatorToken } from "@/lib/operator-auth";
import { quickChoicesForQuestion } from "@/lib/quick-choices";
import { checkoutIntent, stableReferenceId } from "@/lib/razorpay";
import { setCommerceRepositoryForTests } from "@/lib/repository";
import { verifyRazorpaySignature } from "@/lib/webhook";
import type { PreferenceProfile } from "@/lib/types";
import { completePhoneDiscovery, MemoryCommerceRepository, TEST_SESSION_ID } from "@/tests/helpers";

let repository: MemoryCommerceRepository;
const operator = { actorId:"operator_judge",role:"operator" as const,merchantId:"merchant_choosy_demo" };

beforeEach(()=>{ repository=new MemoryCommerceRepository(); setCommerceRepositoryForTests(repository); });
afterEach(()=>{ setCommerceRepositoryForTests(); vi.unstubAllEnvs(); vi.unstubAllGlobals(); });

describe("discovery and ranking boundary",()=>{
  it("keeps category-specific quick choices isolated",()=>{
    expect(quickChoicesForQuestion("size","phones")).toEqual(["Compact","Standard","Large","No preference"]);
    expect(quickChoicesForQuestion("size","phones")).not.toContain("UK 7");
    expect(quickChoicesForQuestion("size","running-shoes")).toEqual(["UK 7","UK 8","UK 9","UK 10"]);
    expect(quickChoicesForQuestion("brandPreference","phones")).toEqual(["No preference","Aster","Northstar","Luma"]);
  });
  it("withholds recommendations until every required answer is explicit",()=>{ const profile=emptyPreferenceProfile(); expect(isProfileComplete(profile)).toBe(false); expect(nextQuestion(profile)?.key).toBe("category"); expect(rankProducts(profile,DEMO_CATALOG)).toEqual([]); });
  it("returns only in-stock products within budget and matching hard must-haves",()=>{ const profile:PreferenceProfile={category:"phones",maxBudgetPaise:50_000_00,useCase:"Photography",brandPreference:"No preference",mustHaves:["camera"],answers:{os:"Android",priority:"Camera",size:"Standard"},confirmedKeys:["category","maxBudgetPaise","useCase","brandPreference","mustHaves","os","priority","size"]}; const results=rankProducts(profile,DEMO_CATALOG); expect(results.length).toBeGreaterThan(0); expect(results.length).toBeLessThanOrEqual(3); for(const result of results){const product=DEMO_CATALOG.find((item)=>item.id===result.productId)!;const variant=product.variants.find((item)=>item.id===result.variantId)!;expect(product.tags).toContain("camera");expect(variant.pricePaise).toBeLessThanOrEqual(profile.maxBudgetPaise!);expect(variant.stock).toBeGreaterThan(0);} });
  it("offers no more than two category-relevant budget-safe add-ons",()=>{ const profile:PreferenceProfile={category:"phones",maxBudgetPaise:50_000_00,useCase:"Everyday",brandPreference:"No preference",mustHaves:[],answers:{os:"Android",priority:"Balanced",size:"Standard"},confirmedKeys:["category","maxBudgetPaise","useCase","brandPreference","mustHaves","os","priority","size"]}; const primary=DEMO_CATALOG.find((item)=>item.sku==="PH-A1")!; const addons=recommendedAddons(profile,primary,DEMO_CATALOG); expect(addons).toHaveLength(2); expect(addons.every((item)=>item.kind==="addon"&&item.category==="phones")).toBe(true); });
});

describe("versioned shopping flow",()=>{
  it("completes discovery, creates a shortlist, and records a valid audit chain",async()=>{ const session=await completePhoneDiscovery(repository); expect(session.phase).toBe("recommendations_ready"); expect(session.recommendations).toHaveLength(3); expect(verifyCommerceAuditChain(session.audit)).toBe(true); expect(session.audit.some((event)=>event.title==="Discovery completeness gate passed")).toBe(true); });
  it("blocks an unavailable item before any Razorpay intent",async()=>{ let session=await completePhoneDiscovery(repository); session=await executeShoppingCommand(TEST_SESSION_ID,{command:"select_product",expectedVersion:session.version,idempotencyKey:"select:test",payload:{productId:session.recommendations[0]!.productId}}); session=await executeShoppingCommand(TEST_SESSION_ID,{command:"set_addons",expectedVersion:session.version,idempotencyKey:"addons:test",payload:{addonIds:[]}}); await markSelectedItemUnavailable(TEST_SESSION_ID,operator); session=await repository.get(TEST_SESSION_ID); session=await executeShoppingCommand(TEST_SESSION_ID,{command:"confirm_cart",expectedVersion:session.version,idempotencyKey:"confirm:test"}); expect(session.phase).toBe("needs_reselection"); expect(session.checkout).toBeNull(); expect(repository.checkouts).toHaveLength(0); expect(session.messages.at(-1)?.text).toContain("nothing was silently substituted"); });
  it("rejects checkout before explicit cart confirmation",async()=>{ const session=await completePhoneDiscovery(repository); await expect(executeShoppingCommand(TEST_SESSION_ID,{command:"create_checkout",expectedVersion:session.version,idempotencyKey:"checkout:early"})).rejects.toThrow("Confirm the current cart"); });
  it("returns the original state for a repeated command idempotency key",async()=>{ const session=await completePhoneDiscovery(repository); const input={command:"select_product" as const,expectedVersion:session.version,idempotencyKey:"select:same",payload:{productId:session.recommendations[0]!.productId}}; const first=await executeShoppingCommand(TEST_SESSION_ID,input); const second=await executeShoppingCommand(TEST_SESSION_ID,{...input,expectedVersion:first.version}); expect(second.version).toBe(first.version); });
  it("receipts repeated messages before applying version checks",async()=>{const initial=await repository.get(TEST_SESSION_ID);const input={text:"Phone",answerKey:"category",answerValue:"Phone",expectedVersion:initial.version,idempotencyKey:"msg:repeat:test"};const first=await sendShoppingMessage(TEST_SESSION_ID,input);const second=await sendShoppingMessage(TEST_SESSION_ID,input);expect(second.version).toBe(first.version);expect(second.messages.filter((item)=>item.text==="Phone")).toHaveLength(1);});
  it("rejects unsupported controlled categories",async()=>{const initial=await repository.get(TEST_SESSION_ID);await expect(sendShoppingMessage(TEST_SESSION_ID,{text:"Laptop",answerKey:"category",answerValue:"Laptop",expectedVersion:initial.version,idempotencyKey:"msg:unsupported"})).rejects.toThrow("not valid");});
  it("reopens an edited preference and removes the stale shortlist",async()=>{const session=await completePhoneDiscovery(repository);const revised=await executeShoppingCommand(TEST_SESSION_ID,{command:"revise_preference",expectedVersion:session.version,idempotencyKey:"revise:budget",payload:{key:"maxBudgetPaise"}});expect(revised.phase).toBe("discovering");expect(revised.activeQuestionKey).toBe("maxBudgetPaise");expect(revised.recommendations).toEqual([]);expect(revised.profile.confirmedKeys).not.toContain("maxBudgetPaise");});
  it("detects cart digest, total, and structural tampering",()=>{const primary=DEMO_CATALOG[0]!;const cart=buildCart(primary,primary.variants[0]!,[]);cart.totalPaise+=100;cart.items[0]!.kind="addon";const result=validateCart(cart,DEMO_CATALOG);expect(result.valid).toBe(false);expect(result.changed).toContain("cart_total");});
  it("rejects a machine quote whose signed fields were altered",async()=>{const primary=DEMO_CATALOG[0]!;const quote=await createMachineQuote([{productId:primary.id,variantId:primary.variants[0]!.id}]);quote.expiresAt=new Date(Date.now()+300000).toISOString();await expect(createMachineCheckout(quote,quote.digest,"machine:tamper")).rejects.toThrow("integrity");});
});

describe("identity and payment safety",()=>{
  it("supports Choosy auth variables and rejects tampered operator tokens",()=>{ vi.stubEnv("CHOOSY_OPERATOR_ACCESS_CODE","judge-access-code");vi.stubEnv("CHOOSY_SESSION_SECRET","choosy-test-session-secret-with-entropy");expect(verifyAccessCode("judge-access-code")).toBe(true);const {token,session}=createOperatorToken("operator_judge",1000);expect(session.merchantId).toBe("merchant_choosy_demo");expect(verifyOperatorToken(token,1001)?.actorId).toBe("operator_judge");expect(verifyOperatorToken(`${token}x`,1001)).toBeNull(); });
  it("creates stable cart-bound references without shopper PII",()=>{ const primary=DEMO_CATALOG[0]!;const cart=buildCart(primary,primary.variants[0]!,[]);const quote={id:"quote_x",cart,catalogVersion:"v1",expiresAt:new Date(Date.now()+60000).toISOString(),digest:"a".repeat(64)};const action=checkoutIntent(TEST_SESSION_ID,quote,"checkout:test");expect(action.referenceId).toBe(stableReferenceId(TEST_SESSION_ID,cart.digest));expect(JSON.stringify(action)).not.toMatch(/email|phone|customer/i); });
  it("verifies Razorpay signatures over the untouched body",()=>{ const body=JSON.stringify({event:"payment.captured"});const signature=createHmac("sha256","secret").update(body).digest("hex");expect(verifyRazorpaySignature(body,signature,"secret")).toBe(true);expect(verifyRazorpaySignature(body,"bad","secret")).toBe(false); });
  it("accepts one exactly correlated paid webhook and ignores its duplicate",async()=>{ const stored=await repository.get(TEST_SESSION_ID);stored.phase="checkout_ready";stored.checkout={id:"checkout_test",sessionId:stored.id,cartId:"cart_test",cartDigest:"b".repeat(64),quoteDigest:"c".repeat(64),idempotencyKey:"checkout:test",referenceId:"chy_test",amountPaise:40000,status:"created",providerId:"plink_test",shortUrl:"https://rzp.io/i/test",requestDigest:"d".repeat(64),createdAt:stored.createdAt,updatedAt:stored.updatedAt};repository.sessions.set(stored.id,stored);const payload={event:"payment_link.paid",payload:{payment_link:{entity:{id:"plink_test",reference_id:"chy_test",amount:40000,notes:{choosy_session_id:stored.id,choosy_cart_digest:"b".repeat(64),choosy_reference_id:"chy_test"}}}}};const rawBody=JSON.stringify(payload);const first=await processRazorpayWebhook({eventId:"evt_paid",eventType:"payment_link.paid",rawBody,payload,sessionId:stored.id});expect(first.state.phase).toBe("paid");const duplicate=await processRazorpayWebhook({eventId:"evt_paid",eventType:"payment_link.paid",rawBody,payload,sessionId:stored.id});expect(duplicate.duplicate).toBe(true);expect(duplicate.state.phase).toBe("paid"); });
  it("records but cannot capture a mismatched webhook amount",async()=>{const stored=await repository.get(TEST_SESSION_ID);stored.phase="checkout_ready";stored.checkout={id:"checkout_amount",sessionId:stored.id,cartId:"cart_amount",cartDigest:"e".repeat(64),quoteDigest:"f".repeat(64),idempotencyKey:"checkout:amount",referenceId:"chy_amount",amountPaise:50000,status:"created",providerId:"plink_amount",requestDigest:"a".repeat(64),createdAt:stored.createdAt,updatedAt:stored.updatedAt};repository.sessions.set(stored.id,stored);const payload={event:"payment_link.paid",payload:{payment_link:{entity:{id:"plink_amount",reference_id:"chy_amount",amount:49999,notes:{choosy_session_id:stored.id,choosy_cart_digest:"e".repeat(64),choosy_reference_id:"chy_amount"}}}}};const result=await processRazorpayWebhook({eventId:"evt_amount",eventType:"payment_link.paid",rawBody:JSON.stringify(payload),payload,sessionId:stored.id});expect(result.ignored).toBe(true);expect(result.state.phase).toBe("checkout_ready");expect(result.state.audit.at(-1)?.title).toContain("amount mismatch");});
});
