"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useMemo, useState } from "react";
import { Activity, ArrowLeft, Box, Check, ExternalLink, LogOut, PackageX, RefreshCw, ShieldCheck, ShoppingBag, Sparkles, WalletCards } from "lucide-react";
import { DEMO_CATALOG } from "@/lib/catalog";
import type { MerchantDashboard, OperatorIdentity } from "@/lib/types";

function percent(value: number): string { return `${Math.round(value * 100)}%`; }
function inr(value: number): string { return `₹${Math.round(value / 100).toLocaleString("en-IN")}`; }
function productName(id: string | null): string { return DEMO_CATALOG.find((item)=>item.id===id)?.name ?? "No product selected"; }

export default function MerchantCockpit({ initialDashboard, operator }: { initialDashboard: MerchantDashboard; operator: OperatorIdentity }) {
  const [dashboard, setDashboard] = useState(initialDashboard); const [selectedId, setSelectedId] = useState(initialDashboard.sessions[0]?.id ?? null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string|null>(null); const [auditFilter,setAuditFilter]=useState("all");
  const selected = useMemo(()=>dashboard.sessions.find((item)=>item.id===selectedId) ?? dashboard.sessions[0], [dashboard, selectedId]);
  const filteredAudit=useMemo(()=>selected?.audit.filter((event)=>auditFilter==="all"||event.kind===auditFilter||event.status===auditFilter)??[],[selected,auditFilter]);
  async function refresh() { setBusy(true); const response=await fetch("/api/merchant/dashboard"); const result=await response.json() as MerchantDashboard&{error?:string}; if(response.ok)setDashboard(result);else setError(result.error??"Refresh failed."); setBusy(false); }
  async function makeUnavailable(){if(!selected)return;setBusy(true);setError(null);const response=await fetch("/api/merchant/inventory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:selected.id,action:"mark_selected_unavailable"})});const result=await response.json() as {error?:string};if(!response.ok)setError(result.error??"Inventory action failed.");await refresh();setBusy(false);}
  async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.reload();}
  const metrics=dashboard.metrics;
  return <main className="cockpit"><header className="cockpit-header"><div><a className="wordmark light" href="/">choosy</a><span>Merchant cockpit</span></div><nav><a href="/"><ArrowLeft size={14}/>Shopper view</a><span>{operator.actorId}</span><button onClick={logout}><LogOut size={14}/>Sign out</button></nav></header>
    <section className="cockpit-hero"><div><p className="eyebrow"><Sparkles size={14}/> Commerce you can prove</p><h1>Every shopper decision,<br/><em>visible and bounded.</em></h1><p>Live demo-session evidence only. No production revenue or conversion lift is claimed.</p></div><div className="integration-row">{Object.entries(dashboard.integration).map(([key,value])=><span key={key}><i className={value?"on":""}/>{key}<b>{String(value).replace("_"," ")}</b></span>)}</div></section>
    <section className="metric-grid"><article><Activity/><span>Sessions</span><strong>{metrics.totalSessions}</strong><small>Anonymous demo journeys</small></article><article><Sparkles/><span>Recommendation rate</span><strong>{percent(metrics.recommendationRate)}</strong><small>Reached a compliant shortlist</small></article><article><ShoppingBag/><span>Cart rate</span><strong>{percent(metrics.cartRate)}</strong><small>Selected a primary item</small></article><article><Box/><span>Add-on attach</span><strong>{percent(metrics.addonAttachRate)}</strong><small>Optional, budget-safe bundles</small></article><article><WalletCards/><span>Checkout rate</span><strong>{percent(metrics.checkoutRate)}</strong><small>Razorpay links created</small></article><article><Check/><span>Test Mode paid</span><strong>{inr(metrics.paidTestModePaise)}</strong><small>Sandbox money only</small></article></section>
    <section className="cockpit-grid"><aside className="session-list"><header><div><p className="eyebrow">Live journeys</p><h2>Shopping sessions</h2></div><button onClick={refresh} disabled={busy}><RefreshCw className={busy?"spin":""} size={15}/></button></header>{dashboard.sessions.length===0&&<div className="empty-list">Start a shopper session to see its decision trail here.</div>}{dashboard.sessions.map((session)=><button key={session.id} className={selected?.id===session.id?"active":""} onClick={()=>setSelectedId(session.id)}><span><i/>{session.phase.replaceAll("_"," ")}</span><strong>{productName(session.selectedProductId)}</strong><small>{session.profile.category?.replace("-"," ")??"Discovering intent"} · v{session.version}</small></button>)}</aside>
      <div className="audit-panel"><header><div><p className="eyebrow">Explainable · bounded · gated</p><h2>Decision audit</h2></div>{selected&&<div className="audit-filter"><select aria-label="Filter audit events" value={auditFilter} onChange={(event)=>setAuditFilter(event.target.value)}><option value="all">All events</option><option value="policy">Policy</option><option value="inventory">Inventory</option><option value="razorpay">Razorpay</option><option value="webhook">Webhooks</option><option value="blocked">Blocked</option></select><span>{filteredAudit.length}/{selected.audit.length} events · {selected.id.slice(-8)}</span></div>}</header>{selected?<><div className="session-summary"><div><span>Phase</span><b>{selected.phase.replaceAll("_"," ")}</b></div><div><span>Budget</span><b>{selected.profile.maxBudgetPaise?inr(selected.profile.maxBudgetPaise):"Not confirmed"}</b></div><div><span>Selected</span><b>{productName(selected.selectedProductId)}</b></div><div><span>Cart</span><b>{selected.cart?inr(selected.cart.totalPaise):"Not built"}</b></div></div><div className="demo-control"><div><PackageX/><span><b>Graceful failure proof</b><small>Mark the selected variant unavailable. The shopper’s next checkout confirmation must stop before Razorpay.</small></span></div><button disabled={busy||!selected.selectedVariantId||selected.phase==="paid"} onClick={makeUnavailable}>Mark unavailable</button></div>{error&&<p className="form-error">{error}</p>}<div className="audit-list">{[...filteredAudit].reverse().map((event)=><article key={event.id}><div className={`audit-icon ${event.status}`}><ShieldCheck size={15}/></div><div><header><b>{event.title}</b><time>{new Date(event.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time></header><p>{event.detail}</p><small>{event.actor} · {event.kind} · hash {event.hash.slice(0,10)}</small></div></article>)}</div></>:<div className="empty-audit"><ShieldCheck/><h3>No session selected</h3><p>The audit trail will reconstruct discovery, ranking, cart approval, inventory checks and Razorpay events.</p></div>}</div>
    </section><footer className="cockpit-footer"><span>Choosy agentic commerce control plane</span><a href="/api/commerce/capabilities" target="_blank">View machine-readable capabilities <ExternalLink size={13}/></a></footer></main>;
}
