import type { CategoryProfile, Product, ProductCategory, ProductVariant } from "@/lib/types";

export const CATALOG_VERSION = "choosy-catalog-2026-09-v3";
export const CATALOG_PRICE_AS_OF = "2026-09-03";
export const CATALOG_MARKET = "India";
export const CATALOG_PRICE_NOTICE = "Real products with frozen Razorpay Test Mode prices; stock is simulated and prices are not live retail offers.";

export const CATEGORY_PROFILES: CategoryProfile[] = [
  { category: "phones", label: "Phones", description: "Smartphones for everyday use, photography, gaming and long battery life", version: "phones-v2", questions: [
    { key: "os", prompt: "Do you prefer Android, iOS, or are you open to either?", choices: ["Android", "iOS", "No preference"], required: true, weight: 16 },
    { key: "priority", prompt: "What matters most: camera, battery, performance, or a balanced phone?", choices: ["Camera", "Battery", "Performance", "Balanced"], required: true, weight: 22 },
    { key: "size", prompt: "What size feels right?", choices: ["Compact", "Standard", "Large", "No preference"], required: true, weight: 10 },
  ] },
  { category: "headphones", label: "Headphones", description: "Personal audio for travel, work, calls and gaming", version: "headphones-v2", questions: [
    { key: "formFactor", prompt: "Which style do you prefer?", choices: ["Over-ear", "Earbuds", "No preference"], required: true, weight: 14 },
    { key: "environment", prompt: "Where will you use them most?", choices: ["Commute", "Office", "Gym", "Gaming"], required: true, weight: 18 },
    { key: "feature", prompt: "Which feature matters most?", choices: ["Noise cancellation", "Low latency", "Call quality", "No preference"], required: true, weight: 18 },
    { key: "connectivity", prompt: "Wireless, wired, or either?", choices: ["Wireless", "Wired", "Either"], required: true, weight: 8 },
  ] },
  { category: "running-shoes", label: "Running shoes", description: "Road and trail shoes for daily training and longer distances", version: "running-shoes-v2", questions: [
    { key: "size", prompt: "What shoe size do you need?", choices: ["UK 7", "UK 8", "UK 9", "UK 10"], required: true, weight: 20 },
    { key: "terrain", prompt: "Where do you usually run?", choices: ["Road", "Trail", "Mixed"], required: true, weight: 18 },
    { key: "distance", prompt: "What does a typical run look like?", choices: ["Under 5 km", "5–10 km", "10 km+", "Walking / casual"], required: true, weight: 14 },
    { key: "cushioning", prompt: "How should the ride feel?", choices: ["Soft", "Balanced", "Responsive", "No preference"], required: true, weight: 12 },
  ] },
];

const variant = (sku: string, label: string, price: number, stock = 8, attributes: Record<string, string> = {}): ProductVariant => ({ id: `var_${sku.toLowerCase()}`, sku, label, pricePaise: price * 100, stock, attributes });

interface CatalogEvidence {
  sourceUrl: string;
  priceKind: "official_mrp" | "official_price" | "retail_snapshot";
  segment: "budget" | "value" | "midrange" | "premium" | "flagship";
  popularitySignal: string;
}

const primary = (sku: string, category: ProductCategory, brand: string, name: string, price: number, tags: string[], description: string, imageUrl: string, catalogEvidence: CatalogEvidence, promoted = false, variants?: ProductVariant[]): Product => ({
  id: `prod_${sku.toLowerCase()}`,
  sku,
  category,
  kind: "primary",
  brand,
  name,
  description,
  imageUrl: `/products/real/${sku.toLowerCase()}.webp`,
  promoted,
  tags,
  attributes: {
    realProduct: true,
    catalogMode: "curated_snapshot",
    market: CATALOG_MARKET,
    priceAsOf: CATALOG_PRICE_AS_OF,
    priceKind: catalogEvidence.priceKind,
    segment: catalogEvidence.segment,
    popularitySignal: catalogEvidence.popularitySignal,
    sourceUrl: catalogEvidence.sourceUrl,
    sourceImageUrl: imageUrl,
    remoteImageUrl: imageUrl,
    stockMode: "simulated",
  },
  variants: variants ?? [variant(`${sku}-STD`, "Standard", price)],
});

const addon = (sku: string, category: ProductCategory, name: string, price: number, tags: string[], description: string): Product => ({
  id: `prod_${sku.toLowerCase()}`,
  sku,
  category,
  kind: "addon",
  brand: "Choosy",
  name,
  description,
  imageUrl: `/products/${category}.png`,
  promoted: false,
  tags,
  attributes: { realProduct: false, catalogMode: "generic_demo_accessory", stockMode: "simulated" },
  variants: [variant(`${sku}-STD`, "Standard", price, 20)],
});

const shoeVariants = (sku: string, price: number) => ["UK 7", "UK 8", "UK 9", "UK 10"].map((size) => variant(`${sku}-${size.replace(" ", "")}`, size, price, 6, { size }));
const evidence = (sourceUrl: string, priceKind: CatalogEvidence["priceKind"], segment: CatalogEvidence["segment"], popularitySignal: string): CatalogEvidence => ({ sourceUrl, priceKind, segment, popularitySignal });

export const CURATED_CATALOG: Product[] = [
  primary("PH-IQ-Z10X", "phones", "iQOO", "iQOO Z10x 5G", 13_499, ["android", "battery", "performance", "large", "gaming", "everyday"], "A high-value Android phone with a 6,500 mAh battery and Dimensity 7300 performance.", "https://www.jiomart.com/images/product/original/rv6lnav4vi/iqoo-z10x-5g-8gb-ram-128gb-storage-ultramarine-smartphone-product-images-orv6lnav4vi-p611504336-0-202505202019.jpg", evidence("https://www.iqoo.com/in/products/z10x", "retail_snapshot", "budget", "Amazon India Electronics bestseller snapshot"), true),
  primary("PH-OP-CE4L", "phones", "OnePlus", "OnePlus Nord CE4 Lite 5G", 19_999, ["android", "battery", "balanced", "standard", "large", "everyday", "camera"], "A value-focused 5G phone with a 5,500 mAh battery, 80W charging, OIS and a 120 Hz AMOLED display.", "https://oasis.opstatics.com/content/dam/oasis/page/2024/camry/share.jpg", evidence("https://www.oneplus.in/nord-ce4-lite-5g", "official_price", "value", "Amazon India Electronics bestseller snapshot")),
  primary("PH-NO-3A", "phones", "Nothing", "Nothing Phone (3a)", 24_999, ["android", "camera", "photography", "balanced", "standard", "large", "everyday"], "A distinctive mid-range Android phone with a 50 MP OIS main camera and dedicated 50 MP telephoto camera.", "https://kontakt.az/media/catalog/product/cache/fbd42596869cc4deb59edfc1ed742a64/t/m/tm-dg-sbp-1105-sm-3876_.png", evidence("https://in.nothing.tech/products/phone-3a", "retail_snapshot", "midrange", "High-volume mid-range launch pick")),
  primary("PH-GO-P8A", "phones", "Google", "Google Pixel 8a", 34_999, ["android", "camera", "photography", "balanced", "compact", "standard", "everyday"], "A compact previous-generation Pixel with a strong computational camera and long software-support window.", "https://www.proshop.de/Images/1600x1200/3265920_c73bf3f210f0.jpg", evidence("https://store.google.com/in/product/pixel_8a?hl=en-IN", "retail_snapshot", "midrange", "Popular compact Pixel value pick")),
  primary("PH-OP-N5", "phones", "OnePlus", "OnePlus Nord 5", 33_999, ["android", "performance", "gaming", "camera", "large", "battery"], "An upper-midrange performance phone with Snapdragon 8s Gen 3, 144 Hz display and 6,800 mAh battery.", "https://1shopmobile.com/wp-content/uploads/2025/07/OnePlus-Nord-5.png", evidence("https://www.oneplus.in/nord-5", "official_price", "midrange", "Current OnePlus Nord performance flagship"), true),
  primary("PH-OP-13R", "phones", "OnePlus", "OnePlus 13R", 42_999, ["android", "performance", "camera", "photography", "battery", "large", "gaming"], "A premium-value Android phone with Snapdragon 8 Gen 3, a 6,000 mAh battery and optical telephoto camera.", "https://static.smartphone.nl/orca/products/27662/oneplus-13r.png?w=1080", evidence("https://www.oneplus.in/13r", "official_price", "premium", "Popular value-flagship series")),
  primary("PH-GO-P9A", "phones", "Google", "Google Pixel 9a", 49_999, ["android", "camera", "photography", "balanced", "standard", "compact", "battery", "everyday"], "A compact camera-first Android phone with a 48 MP main camera, Tensor G4 and seven years of updates.", "https://lh3.googleusercontent.com/0FQnNXFGulZ3DGGAPJJOfgwwAW3qEPyjpWg2SLBkmuIU3-c6FxDcmGBEspqPxKFZzTRHXuiCilf-VlDVAEEZzVb4TeP3JNuKnPQi=rj-sc0xffffffff", evidence("https://store.google.com/in/product/pixel_9a?hl=en-IN", "official_price", "premium", "Google's current value camera phone"), true),
  primary("PH-AP-17E", "phones", "Apple", "Apple iPhone 17e", 64_900, ["ios", "camera", "photography", "performance", "compact", "standard", "balanced", "everyday"], "A compact current-generation iPhone with the A19 chip, a 48 MP Fusion camera and 256 GB storage.", "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17e-finish-unselect-gallery-1-202603_GEO_EMEA?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1770766619343", evidence("https://www.apple.com/in/shop/buy-iphone/iphone-17e", "official_price", "premium", "Current entry iPhone")),
  primary("PH-AP-17", "phones", "Apple", "Apple iPhone 17", 82_900, ["ios", "camera", "photography", "performance", "standard", "balanced", "everyday"], "A current flagship iPhone with A19 performance and a 48 MP Dual Fusion camera system.", "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-finish-unselect-gallery-1-202509_GEO_EMEA?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1758739981039", evidence("https://www.apple.com/in/shop/buy-iphone/iphone-17", "official_price", "flagship", "Current mainstream iPhone flagship")),
  primary("PH-XI-RN14", "phones", "Xiaomi", "Redmi Note 14 5G", 15_999, ["android", "camera", "battery", "balanced", "large", "everyday"], "A popular budget 5G phone with a 108 MP camera, 5,500 mAh battery and 120 Hz AMOLED display.", "https://i02.appmifile.com/349_operator_sg/27/12/2024/a9ad48387db2db77c4a0cd4c88f1c04c.png", evidence("https://www.mi.com/in/redmi-note-14-5g", "retail_snapshot", "budget", "Amazon India Electronics bestseller snapshot")),
  primary("PH-SA-M35", "phones", "Samsung", "Samsung Galaxy M35 5G", 18_999, ["android", "battery", "balanced", "large", "everyday"], "A long-battery Samsung phone with a 6,000 mAh battery, Exynos 1380 and 120 Hz Super AMOLED display.", "https://images.samsung.com/is/image/samsung/p6pim/in/sm-m356blghins/gallery/in-galaxy-m35-5g-sm-m356blghins-thumb-539552065", evidence("https://www.samsung.com/in/smartphones/galaxy-m35-5g/", "official_price", "budget", "Samsung India popular M-series")),
  primary("PH-MO-E60", "phones", "Motorola", "Motorola Edge 60", 24_999, ["android", "camera", "performance", "balanced", "standard", "everyday"], "A mid-range Motorola with a 50 MP OIS camera, Dimensity 7300 and a clean near-stock Android experience.", "https://motorolain.vtexassets.com/arquivos/ids/158282/edge-60-pdp-render-Ocean-Green-702xauto.png", evidence("https://www.motorola.in/smartphones-motorola-edge-60/p", "official_price", "midrange", "Recent Motorola midrange launch")),
  primary("PH-PC-F7", "phones", "Poco", "Poco F7 5G", 25_999, ["android", "performance", "gaming", "camera", "large"], "A performance-focused mid-range phone with Snapdragon 8s Gen 3, 120 Hz AMOLED and 90W fast charging.", "https://i02.appmifile.com/301_operator_sg/08/01/2025/72013d7b32b1c7fa8b3e8a5ead8c0ec6.png", evidence("https://www.poco.in/poco-f7", "retail_snapshot", "midrange", "Popular Poco F-series performance pick"), true),
  primary("PH-RM-GT7", "phones", "Realme", "Realme GT 7", 27_999, ["android", "performance", "gaming", "battery", "large"], "A gaming-oriented phone with Dimensity 9300+, 6,500 mAh battery and a 1.5K LTPO display.", "https://image.realme.net/general/20250301/1740830876443.png", evidence("https://www.realme.com/in/realme-gt-7", "official_price", "midrange", "Realme flagship performance series")),
  primary("PH-SA-A56", "phones", "Samsung", "Samsung Galaxy A56 5G", 29_999, ["android", "camera", "battery", "balanced", "standard", "large", "everyday"], "Samsung's popular A-series mid-ranger with a 50 MP OIS camera, 5,000 mAh battery and One UI 7.", "https://images.samsung.com/is/image/samsung/p6pim/in/sm-a566elbdins/gallery/in-galaxy-a56-5g-sm-a566elbdins-thumb-543765239", evidence("https://www.samsung.com/in/smartphones/galaxy-a56-5g/", "official_price", "midrange", "Bestselling Samsung A-series"), true),
  primary("PH-VI-V50", "phones", "Vivo", "Vivo V50", 34_999, ["android", "camera", "photography", "balanced", "standard", "large", "everyday"], "A photography-focused mid-range phone with ZEISS-tuned 50 MP OIS camera and premium design.", "https://www.vivo.com/content/dam/vivo/in/product/v50/images/v50-hero.png", evidence("https://www.vivo.com/in/v50", "official_price", "midrange", "Vivo India popular V-series")),
  primary("PH-SA-S25", "phones", "Samsung", "Samsung Galaxy S25", 74_999, ["android", "camera", "performance", "compact", "standard", "balanced", "everyday"], "Samsung's compact flagship with Snapdragon 8 Elite, 50 MP triple camera and Galaxy AI features.", "https://images.samsung.com/is/image/samsung/p6pim/in/sm-s931blbdins/gallery/in-galaxy-s25-sm-s931blbdins-thumb-543262684", evidence("https://www.samsung.com/in/smartphones/galaxy-s25/", "official_price", "flagship", "Samsung flagship S-series"), true),
  primary("PH-GO-P9P", "phones", "Google", "Google Pixel 9 Pro", 109_999, ["android", "camera", "photography", "performance", "standard", "balanced"], "Google's premium camera phone with Tensor G4, triple camera system with 5x telephoto and Gemini AI.", "https://lh3.googleusercontent.com/FwpRhSjJaQVLhszpofhMnSjgERYB9mTiBc7rs-OAnXWV9hkJOVGjWClvMHqm2GURKVE_A_YirFmF1HFrDXqH=rj-sc0xffffffff", evidence("https://store.google.com/in/product/pixel_9_pro?hl=en-IN", "official_price", "flagship", "Google flagship camera phone")),
  primary("PH-AP-17P", "phones", "Apple", "Apple iPhone 17 Pro", 119_900, ["ios", "camera", "photography", "performance", "standard", "balanced"], "The Pro iPhone with A19 Pro chip, ProMotion display and advanced triple-camera system with 5x telephoto.", "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-finish-unselect-gallery-1-202509_GEO_EMEA?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1758739981039", evidence("https://www.apple.com/in/shop/buy-iphone/iphone-17-pro", "official_price", "flagship", "Current iPhone Pro model"), true),
  primary("PH-SA-S25U", "phones", "Samsung", "Samsung Galaxy S25 Ultra", 129_999, ["android", "camera", "photography", "performance", "large", "gaming"], "Samsung's ultimate flagship with S Pen, 200 MP main camera, Snapdragon 8 Elite and titanium frame.", "https://images.samsung.com/is/image/samsung/p6pim/in/sm-s938bzkdins/gallery/in-galaxy-s25-ultra-sm-s938bzkdins-thumb-543262654", evidence("https://www.samsung.com/in/smartphones/galaxy-s25-ultra/", "official_price", "flagship", "Samsung Ultra flagship")),
  primary("PH-AP-17PM", "phones", "Apple", "Apple iPhone 17 Pro Max", 144_900, ["ios", "camera", "photography", "performance", "large", "battery"], "The largest and most powerful iPhone with A19 Pro, the longest iPhone battery life and 5x optical zoom.", "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-17-pro-max-finish-unselect-gallery-1-202509_GEO_EMEA?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1758739981039", evidence("https://www.apple.com/in/shop/buy-iphone/iphone-17-pro-max", "official_price", "flagship", "Current iPhone Pro Max model")),

  primary("HD-JB-C100", "headphones", "JBL", "JBL C100SI", 649, ["earbuds", "wired", "call quality", "low latency", "gaming", "office", "everyday"], "Popular wired in-ear headphones with a microphone, one-button remote and zero Bluetooth delay.", "https://in.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw6abf13fa/C100SI_black_dvHAMaster.png?sh=535&sw=535", evidence("https://in.jbl.com/C100SI.html", "official_price", "budget", "Amazon India Electronics bestseller snapshot"), true),
  primary("HD-OP-NB3", "headphones", "OnePlus", "OnePlus Nord Buds 3", 2_299, ["earbuds", "wireless", "noise cancellation", "call quality", "low latency", "gaming", "gym", "commute", "fitness"], "Value true-wireless earbuds with up to 32 dB ANC, low-latency mode and up to 43 hours total playback.", "https://oasis.opstatics.com/content/dam/oasis/page/2024/global/product/mendel/share.jpg", evidence("https://www.oneplus.in/oneplus-nord-buds-3", "retail_snapshot", "budget", "Amazon India Electronics bestseller snapshot"), true),
  primary("HD-JB-Q100", "headphones", "JBL", "JBL Quantum 100M2", 2_499, ["over-ear", "wired", "call quality", "low latency", "gaming", "office"], "A wired over-ear gaming headset with a detachable voice-focus microphone and lossless low-latency audio.", "https://uk.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw3c924442/02.JBL_Quantum%20100M2_Product%20Image_Front_White.png?sh=680&sw=680", evidence("https://in.jbl.com/QUANTUM100M2.html", "official_price", "budget", "Popular entry gaming headset")),
  primary("HD-SO-CH520", "headphones", "Sony", "Sony WH-CH520", 5_990, ["over-ear", "wireless", "call quality", "office", "everyday", "battery"], "Lightweight wireless headphones with up to 50-hour battery life and multipoint connection.", "https://sony.scene7.com/is/image/sonyglobalsolutions/wh-ch520_Primary_image?$S7Product$&fmt=png-alpha", evidence("https://www.sony.co.in/headphones/products/wh-ch520", "official_mrp", "value", "Hundreds of official-store reviews")),
  primary("HD-SO-CH720N", "headphones", "Sony", "Sony WH-CH720N", 14_990, ["over-ear", "wireless", "noise cancellation", "commute", "office", "call quality", "travel"], "Comfortable wireless over-ear headphones with active noise cancellation and beamforming microphones.", "https://sony.scene7.com/is/image/sonyglobalsolutions/wh-ch720_Primary_image?$S7Product$&fmt=png-alpha", evidence("https://www.sony.co.in/headphones/products/wh-ch720n", "official_mrp", "midrange", "Hundreds of official-store reviews"), true),
  primary("HD-AP-A4ANC", "headphones", "Apple", "Apple AirPods 4 with ANC", 17_900, ["earbuds", "wireless", "noise cancellation", "call quality", "gym", "commute", "office", "fitness"], "Open-fit wireless earbuds with active noise cancellation, adaptive audio and voice isolation.", "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-4-select-202409?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1723685836351", evidence("https://www.apple.com/in/airpods-4/", "official_price", "premium", "Current mainstream AirPods model")),
  primary("HD-SO-WF5", "headphones", "Sony", "Sony WF-1000XM5", 29_990, ["earbuds", "wireless", "noise cancellation", "call quality", "commute", "office", "travel"], "Sony's premium compact true-wireless earbuds with flagship noise cancellation and call processing.", "https://sony.scene7.com/is/image/sonyglobalsolutions/Primary_image_black?$S7Product$&fmt=png-alpha", evidence("https://www.sony.co.in/headphones/products/wf-1000xm5", "official_mrp", "premium", "Flagship Sony true-wireless line")),
  primary("HD-SO-XM4", "headphones", "Sony", "Sony WH-1000XM4", 29_990, ["over-ear", "wireless", "noise cancellation", "call quality", "commute", "office", "travel", "battery"], "A widely reviewed premium over-ear ANC headphone with multipoint connection and long battery life.", "https://sony.scene7.com/is/image/sonyglobalsolutions/WH-1000XM4_Primary_image_black?$S7Product$&fmt=png-alpha", evidence("https://www.sony.co.in/headphones/products/wh-1000xm4", "official_mrp", "premium", "More than 2,000 official-store reviews"), true),
  primary("HD-SO-XM6", "headphones", "Sony", "Sony WH-1000XM6", 39_990, ["over-ear", "wireless", "noise cancellation", "call quality", "commute", "office", "travel", "flagship"], "Sony's current flagship wireless over-ear headphone with adaptive noise cancellation and improved microphones.", "https://sony.scene7.com/is/image/sonyglobalsolutions/WH1000XM6_Primary_image_Black?$S7Product$&fmt=png-alpha", evidence("https://www.sony.co.in/headphones/products/wh-1000xm6", "official_price", "flagship", "Current Sony noise-cancelling flagship")),
  primary("HD-BT-AD311", "headphones", "boAt", "boAt Airdopes 311 Pro", 1_299, ["earbuds", "wireless", "call quality", "gym", "commute", "fitness", "everyday"], "India's top-selling budget wireless earbuds with ENx noise-cancelling calls and up to 40 hours playback.", "https://cdn.boat-lifestyle.com/boats/images/variant/Airdopes-311-Pro/Airdopes_311_Pro_Gray.png", evidence("https://www.boat-lifestyle.com/products/airdopes-311-pro", "official_price", "budget", "Amazon India bestselling audio brand"), true),
  primary("HD-RM-BA6", "headphones", "Realme", "Realme Buds Air 6", 1_799, ["earbuds", "wireless", "noise cancellation", "low latency", "gaming", "gym", "commute"], "Budget ANC earbuds with up to 40 dB noise cancellation, 55 ms low-latency mode and LDAC codec.", "https://image.realme.net/general/20240501/1714530456789.png", evidence("https://www.realme.com/in/realme-buds-air-6", "official_price", "budget", "Realme audio bestseller")),
  primary("HD-SA-GBFE", "headphones", "Samsung", "Samsung Galaxy Buds FE", 4_999, ["earbuds", "wireless", "noise cancellation", "call quality", "commute", "office", "fitness"], "Samsung's value ANC earbuds with AKG-tuned sound, three-microphone system and touch controls.", "https://images.samsung.com/is/image/samsung/p6pim/in/sm-r400nzaainu/gallery/in-galaxy-buds-fe-sm-r400nzaainu-thumb-537439225", evidence("https://www.samsung.com/in/audio-video/galaxy-buds-fe/", "official_price", "value", "Popular Samsung buds entry"), true),
  primary("HD-JB-Q350", "headphones", "JBL", "JBL Quantum 350", 5_499, ["over-ear", "wireless", "low latency", "gaming", "call quality"], "A wireless gaming headset with JBL QuantumSURROUND, detachable mic and low-latency 2.4 GHz dongle.", "https://in.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw7bfe9c85/JBL_QUANTUM_350_Product%20Image_Hero.png?sh=535&sw=535", evidence("https://in.jbl.com/gaming/QUANTUM350.html", "official_price", "value", "Popular JBL gaming headset")),
  primary("HD-SO-INZ", "headphones", "Sony", "Sony INZONE Buds", 8_990, ["earbuds", "wireless", "low latency", "gaming", "noise cancellation"], "Gaming-focused wireless earbuds with 2.4 GHz low-latency connection, ANC and 360 spatial sound.", "https://sony.scene7.com/is/image/sonyglobalsolutions/01_WF-G700N_Primary_image_white?$S7Product$&fmt=png-alpha", evidence("https://www.sony.co.in/headphones/products/wf-g700n", "official_price", "value", "Sony gaming audio line")),
  primary("HD-JB-LB3", "headphones", "JBL", "JBL Live Beam 3", 9_999, ["earbuds", "wireless", "noise cancellation", "call quality", "commute", "office", "fitness"], "Premium true-wireless earbuds with Adaptive ANC, touchscreen case and JBL spatial sound.", "https://in.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw0fce3a7b/JBL_LIVE_BEAM3_Hero.png?sh=535&sw=535", evidence("https://in.jbl.com/LIVEBEAM3.html", "official_price", "midrange", "JBL premium earbuds line")),
  primary("HD-JB-T1M2", "headphones", "JBL", "JBL Tour One M2", 19_999, ["over-ear", "wireless", "noise cancellation", "call quality", "commute", "office", "travel"], "JBL's premium over-ear headphones with True Adaptive ANC, 4-mic beamforming and Hi-Res Audio.", "https://in.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw3a18c82d/JBL_Tour_One_M2_Hero.png?sh=535&sw=535", evidence("https://in.jbl.com/TOURONE_M2.html", "official_price", "premium", "JBL premium headphone flagship")),
  primary("HD-BOS-QCE", "headphones", "Bose", "Bose QuietComfort Ultra Earbuds", 24_900, ["earbuds", "wireless", "noise cancellation", "call quality", "commute", "office", "travel"], "Bose's premium ANC earbuds with Immersive Audio, CustomTune and world-class noise cancellation.", "https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/headphones/qc_ultra_earbuds/product_silo_images/QUEBE_SLV_hero.png", evidence("https://www.bose.co.in/p/earbuds/bose-quietcomfort-ultra-earbuds/QUEBE.html", "official_price", "premium", "Bose flagship earbuds")),
  primary("HD-AP-APP2", "headphones", "Apple", "Apple AirPods Pro 2 (USB-C)", 24_900, ["earbuds", "wireless", "noise cancellation", "call quality", "gym", "commute", "office", "fitness"], "Apple's premium ANC earbuds with H2 chip, adaptive transparency, conversation awareness and hearing health.", "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-pro-2-hero-select-202409?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1725492498956", evidence("https://www.apple.com/in/airpods-pro/", "official_price", "premium", "Current AirPods Pro model"), true),
  primary("HD-SN-M4", "headphones", "Sennheiser", "Sennheiser Momentum 4 Wireless", 24_990, ["over-ear", "wireless", "noise cancellation", "call quality", "commute", "office", "travel", "battery"], "Audiophile-grade wireless headphones with adaptive ANC, 60-hour battery life and customisable EQ.", "https://assets.sennheiser.com/img/AssetMaster/x400/product_detail/m4aebt/Product-Image-M4AEBT-Black-Front.png", evidence("https://www.sennheiser.com/en-in/catalog/products/headphones/momentum-4-wireless/momentum-4-wireless-509265", "official_price", "premium", "Sennheiser premium wireless line")),
  primary("HD-BOS-QCH", "headphones", "Bose", "Bose QuietComfort Ultra Headphones", 34_900, ["over-ear", "wireless", "noise cancellation", "call quality", "commute", "office", "travel", "flagship"], "Bose's flagship over-ear headphones with world-class ANC, Immersive Audio and spatial sound.", "https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/headphones/qc_ultra_headphones/product_silo_images/QUCHE_BLK_hero.png", evidence("https://www.bose.co.in/p/headphones/bose-quietcomfort-ultra-headphones/QUIETCOMFORT-ULTRA-HEADPHONES.html", "official_price", "premium", "Bose flagship headphones"), true),
  primary("HD-AP-MAX", "headphones", "Apple", "Apple AirPods Max (USB-C)", 59_900, ["over-ear", "wireless", "noise cancellation", "call quality", "commute", "office", "travel", "flagship"], "Apple's premium over-ear headphones with H2 chip, custom drivers, computational audio and spatial audio.", "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airpods-max-select-202409-midnight?wid=1200&hei=630&fmt=jpeg&qlt=95&.v=1724927451283", evidence("https://www.apple.com/in/airpods-max/", "official_price", "flagship", "Current AirPods Max model")),

  primary("SH-KI-JF190", "running-shoes", "KIPRUN", "KIPRUN JF 190 Grip", 3_299, ["trail", "mixed", "balanced", "under 5 km", "5–10 km", "10 km+", "walking / casual"], "An accessible mixed-surface running shoe with trail-oriented grip and broad community adoption.", "https://contents.mediadecathlon.com/p2819726/e4dc6505412c66165fb2ebb269bac603/p2819726.jpg?format=auto&f=768x0", evidence("https://www.decathlon.in/c/trail-running-shoes-25404", "official_price", "budget", "Thousands of Decathlon customer ratings"), true, shoeVariants("SH-KI-JF190", 3_299)),
  primary("SH-NI-REV8", "running-shoes", "Nike", "Nike Revolution 8", 4_295, ["road", "soft", "balanced", "under 5 km", "walking / casual", "everyday"], "A popular entry road shoe with soft cushioning for short runs, walking and daily wear.", "https://i.ebayimg.com/images/g/K7IAAeSwfAtobrNN/s-l1200.png", evidence("https://www.nike.com/in/w/revolution-running-shoes-37v7jz7yfbz8s9m5", "official_mrp", "budget", "Nike bestseller label"), true, shoeVariants("SH-NI-REV8", 4_295)),
  primary("SH-KI-KS500", "running-shoes", "KIPRUN", "KIPRUN KS500 2", 6_499, ["road", "soft", "responsive", "balanced", "5–10 km", "10 km+"], "A cushioned daily road trainer built for regular middle- and longer-distance running.", "https://contents.mediadecathlon.com/p2602524/k$051982e8fba4d9780102ee7d66f8183e/tenis-de-running-con-mayor-estabilidad-para-hombre-kiprun-ks500-2-negroslashamarillo.jpg", evidence("https://www.decathlon.in/p/8940965/kiprun-ks500-2-men-s-running-shoes-white", "official_price", "value", "Hundreds of high Decathlon ratings"), false, shoeVariants("SH-KI-KS500", 6_499)),
  primary("SH-AD-DUR2", "running-shoes", "adidas", "adidas Duramo SL 2", 6_999, ["road", "balanced", "under 5 km", "5–10 km", "walking / casual", "everyday"], "A lightweight road trainer with LIGHTMOTION cushioning for daily short- and middle-distance runs.", "https://assetmanagerpim-res.cloudinary.com/images/w_450/q_90/62604899a56c494cbac9bfdda64ca55e_9366/IH8217_01_standard.WebP", evidence("https://www.adidas.co.in/duramo-sl-2-running-shoes/IH8217.html", "official_mrp", "value", "More than 2,000 official-store ratings"), false, shoeVariants("SH-AD-DUR2", 6_999)),
  primary("SH-NI-PEG41", "running-shoes", "Nike", "Nike Pegasus 41", 11_895, ["road", "responsive", "balanced", "5–10 km", "10 km+"], "A bestseller daily road trainer with ReactX foam and dual Air Zoom units for an energised ride.", "https://static.nike.com/a/images/t_PDP_864_v1%2Cf_auto%2Cq_auto%3Aeco/9d45f2da-011a-416f-84dd-6c1cb740d4b8/pegasus-41-womens-road-running-shoes-tSbZGh.png", evidence("https://www.nike.com/in/t/pegasus-41-road-running-shoes-Gbj6Js", "official_mrp", "midrange", "Nike bestseller label"), true, shoeVariants("SH-NI-PEG41", 11_895)),
  primary("SH-NI-PGT5", "running-shoes", "Nike", "Nike Pegasus Trail 5", 12_795, ["trail", "mixed", "balanced", "responsive", "5–10 km", "10 km+"], "A road-to-trail trainer with responsive cushioning and dependable mixed-surface traction.", "https://www.nike.sa/dw/image/v2/BDVB_PRD/on/demandware.static/-/Sites-akeneo-master-catalog/default/dw28b80db2/nk/7e8/0/6/4/3/8/7e806438_7c44_4391_a2fa_4713bb7d77fc.jpg", evidence("https://www.nike.com/in/t/pegasus-trail-5-trail-running-shoes-2jxMFQ/DV3864-009", "official_mrp", "midrange", "Highly rated Pegasus trail line"), true, shoeVariants("SH-NI-PGT5", 12_795)),
  primary("SH-AD-BOS13", "running-shoes", "adidas", "adidas Adizero Boston 13", 15_999, ["road", "responsive", "5–10 km", "10 km+", "performance"], "A fast training shoe with Lightstrike Pro cushioning and ENERGYRODS for tempo and long runs.", "https://assetmanagerpim-res.cloudinary.com/images/w_1560/q_100/0b7c71ea1642448281858d43b1089a2c_9366/JS4932_01_00_standard.WebP", evidence("https://www.adidas.co.in/adizero-boston-13-shoes/JS4945.html", "official_mrp", "premium", "Hundreds of official-store ratings"), true, shoeVariants("SH-AD-BOS13", 15_999)),
  primary("SH-NI-VF4", "running-shoes", "Nike", "Nike Vaporfly 4", 21_495, ["road", "responsive", "10 km+", "performance", "race"], "A lightweight carbon-plated road racing shoe for faster 10K, half-marathon and marathon efforts.", "https://static.nike.com/a/images/t_default/117eaf48-f736-44cf-9619-abf75a7e4320/ZOOMX%2BVAPORFLY%2BNEXT%25%2B4.png", evidence("https://www.nike.com/in/w/vaporfly-running-shoes-37v7jz7yfbz8n3yx", "official_mrp", "flagship", "Nike bestseller race shoe"), false, shoeVariants("SH-NI-VF4", 21_495)),
  primary("SH-SK-GRC2", "running-shoes", "Skechers", "Skechers GO RUN Consistent 2.0", 3_499, ["road", "soft", "under 5 km", "walking / casual", "everyday"], "An accessible cushioned shoe for short runs, walking and daily wear with lightweight ULTRA GO midsole.", "https://www.skechers.in/dw/image/v2/BFKL_PRD/on/demandware.static/-/Sites-sklobal-Library/default/dw3b7e6c42/220389/220389_NVY_hero.jpg", evidence("https://www.skechers.in/men/shoes/walking/", "retail_snapshot", "budget", "Skechers India popular running shoe"), false, shoeVariants("SH-SK-GRC2", 3_499)),
  primary("SH-AS-GC9", "running-shoes", "ASICS", "ASICS Gel-Contend 9", 4_499, ["road", "balanced", "under 5 km", "walking / casual", "everyday"], "An entry-level road shoe with GEL technology cushioning and a comfortable everyday fit.", "https://images.asics.com/is/image/asics/1011B911_005_SR_RT_GLB-1?$sfcc-product$", evidence("https://www.asics.com/in/running-shoes/", "retail_snapshot", "budget", "ASICS entry running shoe"), false, shoeVariants("SH-AS-GC9", 4_499)),
  primary("SH-NB-680", "running-shoes", "New Balance", "New Balance Fresh Foam 680v8", 6_499, ["road", "soft", "5\u201310 km", "walking / casual", "balanced"], "A versatile daily shoe with Fresh Foam cushioning for comfortable middle-distance runs and walking.", "https://nb.scene7.com/is/image/NB/m680lb8_nb_05_i?$pdpPictLG$", evidence("https://www.newbalance.co.in/running/", "retail_snapshot", "value", "New Balance popular daily trainer"), false, shoeVariants("SH-NB-680", 6_499)),
  primary("SH-PM-VN3", "running-shoes", "Puma", "Puma Velocity NITRO 3", 7_999, ["road", "responsive", "5\u201310 km", "10 km+", "balanced"], "A nitrogen-infused daily trainer with NITRO foam for responsive cushioning across distances.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/379610/01/sv01/fnd/IND/fmt/png", evidence("https://in.puma.com/in/en/running/", "retail_snapshot", "value", "Puma popular running series"), true, shoeVariants("SH-PM-VN3", 7_999)),
  primary("SH-BR-GH16", "running-shoes", "Brooks", "Brooks Ghost 16", 12_999, ["road", "balanced", "soft", "5\u201310 km", "10 km+", "everyday"], "A trusted daily trainer with DNA LOFT cushioning that balances softness and smooth transitions.", "https://www.brooksrunning.com/dw/image/v2/BGBF_PRD/on/demandware.static/-/Sites-brooks-master-catalog/default/dw44d7e7d0/110418/110418_093_l_Ghost16.png", evidence("https://www.brooksrunning.com/en_in/ghost-16/", "retail_snapshot", "midrange", "Brooks bestselling neutral shoe"), false, shoeVariants("SH-BR-GH16", 12_999)),
  primary("SH-SL-SC6", "running-shoes", "Salomon", "Salomon Speedcross 6", 12_999, ["trail", "responsive", "10 km+", "performance"], "An aggressive trail shoe with Contagrip MA traction, Sensifit cradle and EnergyCell+ cushioning.", "https://www.salomon.com/sites/default/files/styles/product-swatch/public/product/L41737900_0_GHO_SPEEDCROSS%206_Black.png", evidence("https://www.salomon.com/en-in/shop/product/speedcross-6.html", "retail_snapshot", "midrange", "Iconic Salomon trail shoe"), false, shoeVariants("SH-SL-SC6", 12_999)),
  primary("SH-NB-RBL4", "running-shoes", "New Balance", "New Balance FuelCell Rebel v4", 12_999, ["road", "responsive", "5\u201310 km", "10 km+", "performance"], "A lightweight, fast daily trainer with FuelCell cushioning for speed sessions and tempo runs.", "https://nb.scene7.com/is/image/NB/mfcxlb4_nb_05_i?$pdpPictLG$", evidence("https://www.newbalance.co.in/running/", "retail_snapshot", "midrange", "Popular New Balance speed trainer"), false, shoeVariants("SH-NB-RBL4", 12_999)),
  primary("SH-HK-CL10", "running-shoes", "Hoka", "Hoka Clifton 10", 13_990, ["road", "soft", "5\u201310 km", "10 km+", "balanced", "everyday"], "A lightweight max-cushion daily trainer with extended PEBA-blend foam for a cloud-like ride.", "https://img.hoka.com/is/image/hoka/1160042-BWHT_1?$pdp_1920x$&fmt=webp&qlt=90", evidence("https://www.hoka.com/en/in/clifton-10/", "retail_snapshot", "midrange", "Hoka bestselling daily trainer"), true, shoeVariants("SH-HK-CL10", 13_990)),
  primary("SH-AS-NIM27", "running-shoes", "ASICS", "ASICS Gel-Nimbus 27", 14_999, ["road", "soft", "10 km+", "performance", "balanced"], "A premium neutral running shoe with PureGEL cushioning and FF BLAST PLUS foam for long-distance comfort.", "https://images.asics.com/is/image/asics/1011C025_001_SR_RT_GLB-1?$sfcc-product$", evidence("https://www.asics.com/in/gel-nimbus-27/", "retail_snapshot", "premium", "ASICS premium neutral shoe"), true, shoeVariants("SH-AS-NIM27", 14_999)),
  primary("SH-HK-SG6", "running-shoes", "Hoka", "Hoka Speedgoat 6", 15_990, ["trail", "responsive", "balanced", "10 km+", "performance"], "A versatile trail shoe with Vibram Megagrip outsole and improved PROFLY+ midsole for technical terrain.", "https://img.hoka.com/is/image/hoka/1160016-CSMS_1?$pdp_1920x$&fmt=webp&qlt=90", evidence("https://www.hoka.com/en/in/speedgoat-6/", "retail_snapshot", "premium", "Hoka flagship trail shoe"), true, shoeVariants("SH-HK-SG6", 15_990)),
  primary("SH-AS-KAY31", "running-shoes", "ASICS", "ASICS Gel-Kayano 31", 16_999, ["road", "soft", "balanced", "10 km+", "performance"], "A premium stability shoe with PureGEL and 4D GUIDANCE SYSTEM for overpronation support on long runs.", "https://images.asics.com/is/image/asics/1011C026_001_SR_RT_GLB-1?$sfcc-product$", evidence("https://www.asics.com/in/gel-kayano-31/", "retail_snapshot", "premium", "ASICS flagship stability shoe"), false, shoeVariants("SH-AS-KAY31", 16_999)),
  primary("SH-AD-UB5", "running-shoes", "adidas", "adidas Ultraboost 5", 16_999, ["road", "soft", "balanced", "5\u201310 km", "10 km+", "everyday"], "A premium lifestyle-crossover runner with full-length BOOST cushioning and Primeknit+ upper.", "https://assetmanagerpim-res.cloudinary.com/images/w_1560/q_100/a5bfa4a45f4243889f3c3e21e07adb67_9366/ID3473_01_standard.WebP", evidence("https://www.adidas.co.in/ultraboost-5-shoes/ID3473.html", "official_mrp", "premium", "Iconic adidas Ultraboost series"), false, shoeVariants("SH-AD-UB5", 16_999)),

  addon("AC-P1", "phones", "30W compact charger", 1_499, ["phones", "battery", "charging"], "A generic demo charger used only to prove a relevant, budget-safe add-on."),
  addon("AC-P2", "phones", "Everyday protective case", 999, ["phones", "protection", "everyday"], "A generic demo case used only to prove a relevant, budget-safe add-on."),
  addon("AC-H1", "headphones", "Travel hard case", 1_199, ["headphones", "commute", "protection"], "A generic demo travel case for over-ear headphones."),
  addon("AC-H2", "headphones", "Comfort ear-tip set", 699, ["headphones", "earbuds", "gym"], "A generic demo ear-tip set for compatible in-ear headphones."),
  addon("AC-S1", "running-shoes", "Performance running socks", 799, ["running-shoes", "road", "trail"], "A generic demo two-pair running sock bundle."),
  addon("AC-S2", "running-shoes", "Reflective run band", 599, ["running-shoes", "road", "safety"], "A generic demo reflective band for low-light runs."),
  addon("AC-P3", "phones", "Tempered glass screen protector", 599, ["phones", "protection", "everyday"], "A generic demo screen protector used only to prove a relevant, budget-safe add-on."),
  addon("AC-P4", "phones", "65W GaN fast charger", 2_499, ["phones", "battery", "charging", "performance"], "A generic demo GaN charger used only to prove a relevant, budget-safe add-on."),
  addon("AC-H3", "headphones", "Replacement ear cushions", 899, ["headphones", "over-ear", "comfort"], "A generic demo cushion set for over-ear headphones."),
  addon("AC-H4", "headphones", "Bluetooth audio transmitter", 1_299, ["headphones", "wired", "wireless", "connectivity"], "A generic demo Bluetooth transmitter for wired headphones."),
  addon("AC-S3", "running-shoes", "Comfort insole kit", 999, ["running-shoes", "road", "trail", "comfort"], "A generic demo insole kit for running shoes."),
  addon("AC-S4", "running-shoes", "Trail gaiters", 699, ["running-shoes", "trail", "protection"], "A generic demo trail gaiter pair for trail runs."),
];

// Backwards-compatible name while existing modules migrate to the clearer catalog terminology.
export const DEMO_CATALOG = CURATED_CATALOG;

export function categoryProfile(category: ProductCategory): CategoryProfile { return CATEGORY_PROFILES.find((item) => item.category === category)!; }
export function productById(id: string, catalog = CURATED_CATALOG): Product | undefined { return catalog.find((item) => item.id === id); }
export function variantById(product: Product, id: string): ProductVariant | undefined { return product.variants.find((item) => item.id === id); }
