import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Check, FlaskConical, ShieldCheck } from "lucide-react";
import { GROWTH_POLICY } from "@/lib/commerce-policy";
import { runGrowthBenchmark } from "@/lib/growth-benchmark";

function inr(value: number): string { return `₹${Math.round(value / 100).toLocaleString("en-IN")}`; }
function percent(value: number): string { return `${Math.round(value * 100)}%`; }

export default function EvidencePage() {
  const report = runGrowthBenchmark();
  return <main className="evidence-shell">
    <header className="evidence-header"><Link className="wordmark" href="/">choosy</Link><nav><Link href="/"><ArrowLeft size={14}/>Shop</Link><Link href="/agent-buyer">Let AI do the work</Link><Link href="/merchant">Merchant dashboard</Link></nav></header>
    <section className="evidence-hero"><p className="eyebrow"><FlaskConical size={14}/> How we test</p><h1>See how Choosy<br/><em>performs.</em></h1><p>We run the same 100 test shopping scenarios through a basic product list and through Choosy, using the same products, prices, and purchase rules.</p></section>
    <section className="evidence-score simple"><article><span>Successful test baskets</span><strong>{report.choosy.completedPurchases} / {report.datasetSize}</strong><small>All stated needs were met</small></article><article><span>Missed requirements</span><strong>{report.choosy.hardConstraintViolations}</strong><small>Across all 100 Choosy scenarios</small></article><article><span>Relevant extras</span><strong>{percent(report.choosy.relevantAddonAttachRate)}</strong><small>Added only when requested and affordable</small></article></section>
    <details className="full-test"><summary>See the full test</summary><div className="evidence-grid"><article className="comparison-card"><header><div><p className="eyebrow">Side by side</p><h2>Same shoppers, different results</h2></div><span className={report.gates.passed?"gate-pass":"gate-fail"}><Check size={14}/> Checks passed</span></header><table><thead><tr><th>Test result</th><th>Basic list</th><th>Choosy</th></tr></thead><tbody><tr><td>Successful test baskets</td><td>{report.baseline.completedPurchases}</td><td>{report.choosy.completedPurchases}</td></tr><tr><td>Test basket value</td><td>{inr(report.baseline.simulatedGmvPaise)}</td><td>{inr(report.choosy.simulatedGmvPaise)}</td></tr><tr><td>Average basket</td><td>{inr(report.baseline.averageOrderValuePaise)}</td><td>{inr(report.choosy.averageOrderValuePaise)}</td></tr><tr><td>Relevant extras</td><td>{percent(report.baseline.relevantAddonAttachRate)}</td><td>{percent(report.choosy.relevantAddonAttachRate)}</td></tr><tr><td>Missed requirements</td><td>{report.baseline.hardConstraintViolations}</td><td>{report.choosy.hardConstraintViolations}</td></tr></tbody></table></article>
      <aside className="method-card"><p className="eyebrow">How the test works</p><h2>What these numbers mean</h2><p>The basic list filters by product type, budget, and stock. Choosy uses those same checks plus the shopper’s stated preferences.</p><ul><li><ShieldCheck size={14}/>A basket succeeds only when every required feature matches</li><li><ShieldCheck size={14}/>An extra counts only when the shopper asked for it</li><li><ShieldCheck size={14}/>These are test results, not real customer conversion data</li></ul><dl><div><dt>Test version</dt><dd>{report.methodologyVersion}</dd></div><div><dt>Fixture fingerprint</dt><dd>{report.fixtureDigest.slice(0,12)}…</dd></div><div><dt>Last run</dt><dd>{new Date(report.generatedAt).toLocaleDateString("en-IN")}</dd></div></dl></aside></div></details>
    <section className="policy-strip"><div><p className="eyebrow">Built-in safeguards</p><h2>The shopper’s needs come first.</h2></div><span>Budget always respected</span><span>At most {GROWTH_POLICY.maximumAddons} useful extras</span><span>Approval required before payment</span><Link href="/agent-api">For developers <ArrowUpRight size={13}/></Link></section>
  </main>;
}
